--1.
SELECT COUNT(CODFAC) FROM FACTURAS
WHERE NVL(IVA, 0) IN (SELECT IVA FROM FACTURAS
			WHERE IVA=16)
			
SELECT COUNT(CODFAC) FROM FACTURAS
WHERE NVL(IVA, 0) = 16

--2.
SELECT COUNT(CODFAC) FROM FACTURAS
WHERE NVL(IVA, 0) NOT IN (SELECT IVA FROM FACTURAS
					WHERE IVA=16)
					
SELECT COUNT(CODFAC) FROM FACTURAS
WHERE NVL(IVA, 0) != 16

--3.
SELECT COUNT(CODFAC) FROM FACTURAS
WHERE NVL(IVA, 0) IN (SELECT IVA FROM FACTURAS
			WHERE IVA=16)
			
SELECT COUNT(CODFAC) FROM FACTURAS
WHERE NVL(IVA, 0) = ALL 16

--4.
SELECT FECHA FROM FACTURAS F, LINEAS_FAC LF
WHERE F.CODFAC = LF.CODFAC 
AND LF.PRECIO = (SELECT MAX(PRECIO) FROM LINEAS_FAC)

--5.
SELECT COUNT(CODCLI) FROM CLIENTES
WHERE CODPUE NOT IN (SELECT CODPUE FROM PUEBLOS)

SELECT COUNT(C.CODCLI) FROM CLIENTES C, PUEBLOS P
WHERE C.CODPUE(+) = P.CODPUE
AND C.CODPUE IS NULL

--6.
SELECT COUNT(CODART) FROM ARTICULOS
WHERE CODART IN (SELECT CODART FROM LINEAS_FAC
					WHERE CODFAC IN (SELECT CODFAC FROM FACTURAS
									WHERE EXTRACT(MONTH FROM FECHA) > '9'))
AND STOCK > 20
AND PRECIO > 15 

SELECT COUNT(A.CODART) FROM ARTICULOS A, LINEAS_FAC LF, FACTURAS F
WHERE A.CODART = LF.CODART
AND LF.CODFAC = F.CODFAC
AND A.STOCK > 20
AND A.PRECIO > 15
AND EXTRACT(MONTH FROM F.FECHA) > '9'

--7.
SELECT COUNT(CODCLI) FROM CLIENTES
WHERE CODCLI IN (SELECT CODCLI FROM FACTURAS
					WHERE IVA = 0 OR IVA IS NULL)

--8.
SELECT C.CODCLI, C.NOMBRE FROM CLIENTES C, (SELECT F.CODCLI
											FROM LINEAS_FAC LF, FACTURAS F
											WHERE LF.CODFAC = F.CODFAC
											AND EXTRACT(YEAR FROM F.FECHA) = EXTRACT(YEAR FROM SYSDATE)-1
											AND EXTRACT(MONTH FROM F.FECHA) = 11
											GROUP BY F.CODCLI
											HAVING SUM(LF.PRECIO) > 60.50) CLIENTE_PREFERENTE
--9.
SELECT A.CODART, A.DESCRIP, A.PRECIO FROM (SELECT A.CODART, A.DESCRIP, A.PRECIO
											FROM ARTICULOS A
											ORDER BY A.PRECIO DESC) A
WHERE ROWNUM < 11

--10.


--11.
SELECT CODART, DESCRIP FROM ARTICULOS
WHERE CODART IN (SELECT CODART FROM LINEAS_FAC
					WHERE CANT IN (SELECT SUM(CANT) FROM LINEAS_FAC
									WHERE CODFAC IN (SELECT CODFAC FROM FACTURAS
														WHERE EXTRACT(YEAR FROM FECHA) = '2021')
									GROUP BY CODART
									HAVING SUM(CANT) < 10))
AND PRECIO > 90.15

--12.
SELECT CODART, DESCRIP FROM ARTICULOS
WHERE PRECIO > (SELECT MIN(PRECIO)*3000 FROM ARTICULOS)
					
--13.
SELECT C.NOMBRE FROM CLIENTES C, LINEAS_FAC LF2, FACTURAS F
WHERE C.CODCLI = LF2.CODFAC
AND F.CODFAC = LF2.CODFAC
GROUP BY C.NOMBRE
HAVING SUM(LF2.PRECIO) = (SELECT MAX(SUM(LF.PRECIO)) FROM LINEAS_FAC LF, FACTURAS F2, CLIENTES C2
						WHERE LF.CODFAC = F2.CODFAC
						AND F2.CODCLI = C2.CODCLI
						GROUP BY C2.CODCLI)

--14.
SELECT A.CODART, A.DESCRIP FROM ARTICULOS A, LINEAS_FAC LF, FACTURAS F 
WHERE A.CODART = LF.CODART
AND LF.CODFAC = F.CODFAC
AND F.CODCLI IN (SELECT F2.CODCLI FROM FACTURAS F2, LINEAS_FAC LF2
					WHERE F2.CODFAC = LF2.CODFAC
					GROUP BY LF2.CODART, F2.CODCLI
					HAVING COUNT(F2.CODCLI) > 5)
AND A.PRECIO > (SELECT AVG(PRECIO) FROM ARTICULOS)
					
					
