--1.
SELECT ROUND(AVG(NVL(SALDO, 0)), 2), SUM(NVL(SALDO, 0)) 
FROM CUENTA

--2.
SELECT MIN(SALDO), MAX(SALDO), TRUNC(AVG(NVL(SALDO, 0)), 2) FROM CUENTA

--3.
SELECT DISTINCT SUM(NVL(SALDO, 0)), AVG(NVL(SALDO, 0)) FROM CUENTA
GROUP BY COD_CUENTA

--4.
SELECT CLI.COD_CLIENTE, SUM(NVL(C.SALDO, 0)), COUNT(NVL(COD_CUENTA, 0))
FROM CLIENTE CLI, CUENTA C
WHERE CLI.COD_CLIENTE = C.COD_CLIENTE
GROUP BY CLI.COD_CLIENTE

--5.
SELECT NOMBRE, APELLIDOS, SUM(NVL(C.SALDO, 0)), COUNT(NVL(COD_CUENTA, 0)) 
FROM CLIENTE CLI, CUENTA C
WHERE CLI.COD_CLIENTE = C.COD_CLIENTE
GROUP BY NOMBRE, APELLIDOS

--6.
SELECT S.DIRECCION, COUNT(C.COD_CUENTA), SUM(C.SALDO)
FROM SUCURSAL S, CUENTA C
WHERE C.COD_SUCURSAL = S.COD_SUCURSAL
GROUP BY S.COD_SUCURSAL, S.DIRECCION

--7.
SELECT AVG(NVL(SALDO, 0)), AVG(NVL(INTERES, 0))
FROM CUENTA
WHERE INTERES > 0.10
AND (COD_SUCURSAL = 1 OR COD_SUCURSAL = 2)

--13.
SELECT SUM(M.IMPORTE), CL.NOMBRE, CL.APELLIDOS, C.COD_CUENTA, TM.DESCRIPCION
FROM CLIENTE CL, CUENTA C, 

--14.
SELECT COUNT(DISTINCT C.COD_CUENTA) 
FROM CUENTA C, MOVIMIENTO M
WHERE C.COD_CUENTA = M.COD_CUENTA(+)
AND M.COD_CUENTA IS NULL

SELECT COUNT(DISTINCT C.COD_CUENTA) 
FROM CUENTA C, MOVIMIENTO M
WHERE C.COD_CUENTA NOT IN (SELECT M.COD_CUENTA FROM MOVIMIENTO M)

--15.
SELECT C.COD_CLIENTE, COUNT(C.COD_CUENTA)
FROM CUENTA C, MOVIMIENTO M
WHERE C.COD_CUENTA = M.COD_CUENTA(+)
AND M.COD_CUENTA IS NULL
GROUP BY C.COD_CLIENTE

SELECT C.COD_CLIENTE, COUNT(C.COD_CUENTA)
FROM CUENTA C
WHERE C.COD_CUENTA NOT IN (SELECT COD_CUENTA FROM MOVIMIENTO)
GROUP BY C.COD_CLIENTE

--16.
SELECT COD_CLIENTE, SUM(SALDO), COUNT(COD_CUENTA)
FROM CUENTA
GROUP BY COD_CLIENTE
HAVING SUM(SALDO) > 35000

--17.
SELECT CL.NOMBRE, CL.APELLIDOS, COUNT(C.COD_CUENTA)
FROM CLIENTE CL, CUENTA C
WHERE C.COD_CLIENTE = CL.COD_CLIENTE
GROUP BY C.COD_CLIENTE, CL.NOMBRE


--19.
SELECT M.COD_CUENTA, C.SALDO, TM.DESCRIPCION, SUM(M.IMPORTE)
FROM CUENTA C, MOVIMIENTO M, TIPO_MOVIMIENTO TM
WHERE C.COD_CUENTA = M.COD_CUENTA
AND M.COD_TIPO_MOVIMIENTO = TM.COD_TIPO_MOVIMIENTO
GROUP BY M.COD_CUENTA, C.SALDO, TM.DESCRIPCION, M.NUM_MOV_MES
HAVING SUM(M.IMPORTE) > C.SALDO * 0.20

--20.
SELECT C.COD_CUENTA, C.SALDO, TM.DESCRIPCION, SUM(M.IMPORTE)
FROM CUENTA C, MOVIMIENTO M, TIPO_MOVIMIENTO TM, SUCURSAL S
WHERE C.COD_CUENTA = M.COD_CUENTA
AND M.COD_TIPO_MOVIMIENTO = TM.COD_TIPO_MOVIMIENTO
AND S.COD_SUCURSAL = C.COD_SUCURSAL
AND S.COD_SUCURSAL NOT LIKE 4
GROUP BY C.COD_CUENTA, C.SALDO, TM.DESCRIPCION
HAVING SUM(M.IMPORTE) > (C.SALDO * 0.10)

--21.
SELECT CL.* FROM CLIENTE CL, CUENTA C, SUCURSAL S
WHERE CL.COD_CLIENTE = C.COD_CLIENTE
AND C.COD_SUCURSAL = S.COD_SUCURSAL
GROUP BY CL.COD_CLIENTE, CL.NOMBRE, CL.APELLIDOS, CL.DIRECCION, C.SALDO, S.CAPITAL_ANIO_ANTERIOR
HAVING SUM(C.SALDO) >= (S.CAPITAL_ANIO_ANTERIOR * 0.20)