--1.
SELECT COUNT(NVL(COSTEBASICO,0)) FROM ASIGNATURA

--2.
SELECT T.NOMBRE, COUNT(IDASIGNATURA) FROM TITULACION T, ASIGNATURA A
WHERE T.IDTITULACION = A.IDTITULACION
GROUP BY T.NOMBRE

--3.
SELECT T.NOMBRE, SUM(A.COSTEBASICO) FROM TITULACION T, ASIGNATURA A
WHERE T.IDTITULACION = A.IDTITULACION
GROUP BY T.NOMBRE

--4.
SELECT SUM(A.COSTEBASICO * 1.07) COSTEGLOBAL FROM TITULACION T, ASIGNATURA A
WHERE A.IDTITULACION = 130110
AND T.NOMBRE = 'Matematicas'

--5.
SELECT IDASIGNATURA, COUNT(IDALUMNO) FROM ALUMNO_ASIGNATURA
GROUP BY IDASIGNATURA

--6.
SELECT A.NOMBRE, COUNT(AA.IDALUMNO) FROM ALUMNO_ASIGNATURA AA, ASIGNATURA A
WHERE A.IDASIGNATURA = AA.IDASIGNATURA
GROUP BY A.NOMBRE

--7.
SELECT P.NOMBRE, SUM(NVL(A.COSTEBASICO,0)) AS "TOTAL" 
FROM PERSONA P, ASIGNATURA A, ALUMNO_ASIGNATURA AA, ALUMNO AL
WHERE AL.IDALUMNO = AA.IDALUMNO 
AND AL.DNI = P.DNI 
AND A.IDASIGNATURA = AA.IDASIGNATURA
GROUP BY P.NOMBRE

--8.
SELECT AVG(A.COSTEBASICO), T.NOMBRE FROM ASIGNATURA A, TITULACION T, ALUMNO_ASIGNATURA AA
WHERE T.IDTITULACION = A.IDTITULACION
AND AA.IDASIGNATURA = A.IDASIGNATURA
GROUP BY T.NOMBRE
HAVING SUM(A.COSTEBASICO) > 60 AND AA.NUMEROMATRICULA=1


--9.
SELECT T.NOMBRE FROM ALUMNO AL, ALUMNO_ASIGNATURA AA, ASIGNATURA A, TITULACION T
WHERE AL.IDALUMNO = AA.IDALUMNO 
AND AA.IDASIGNATURA = A.IDASIGNATURA 
AND T.IDTITULACION = A.IDTITULACION
GROUP BY T.NOMBRE
HAVING COUNT(AL.IDALUMNO) > 3

--10.
SELECT CIUDAD, COUNT(NOMBRE) FROM PERSONA
GROUP BY CIUDAD

--11.
SELECT P.NOMBRE, COUNT(A.IDASIGNATURA) FROM ASIGNATURA A, PROFESOR PR, PERSONA P
WHERE A.IDPROFESOR = PR.IDPROFESOR 
AND P.DNI = PR.DNI
GROUP BY P.NOMBRE

--12.
SELECT P.NOMBRE, COUNT(AA.IDALUMNO) FROM PERSONA P, ALUMNO AL, ALUMNO_ASIGNATURA AA, ASIGNATURA A, PROFESOR PR
WHERE AL.IDALUMNO = AA.IDALUMNO 
AND PR.DNI = P.DNI 
AND PR.IDPROFESOR = A.IDPROFESOR 
AND A.IDASIGNATURA = AA.IDASIGNATURA
GROUP BY P.NOMBRE
HAVING COUNT(AA.IDALUMNO) >= 3

--13.
SELECT MAX(SUM(COSTEBASICO)) FROM ASIGNATURA
GROUP BY IDASIGNATURA

--14.
SELECT SUM(COSTEBASICO) FROM ASIGNATURA

--15.
SELECT COUNT(IDASIGNATURA) FROM ASIGNATURA

--16.
SELECT MAX(COSTEBASICO), MIN(COSTEBASICO) FROM ASIGNATURA

--17.
SELECT COUNT(DISTINCT CREDITOS) FROM ASIGNATURA

--18.
SELECT COUNT(DISTINCT NVL(CURSO,0)) FROM ASIGNATURA

--19.
SELECT COUNT(DISTINCT CIUDAD) FROM PERSONA

--20.
SELECT A.NOMBRE, (A.CREDITOS *10) AS NUM_HORAS FROM ASIGNATURA A

--21.
SELECT * FROM ASIGNATURA A, TITULACION T
WHERE A.IDTITULACION IN T.IDTITULACION

--22.
SELECT NOMBRE || ' ' ||APELLIDO AS NOMBRECOMPLETO, DIRECCIONCALLE || ' ' || DIRECCIONNUM AS DIRECCION, TELEFONO 
FROM PERSONA

--23.
SELECT SUM(EXTRACT(DAY FROM FECHA_NACIMIENTO)+1) FROM PERSONA
GROUP BY DNI

--24.
SELECT EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM FECHA_NACIMIENTO) FROM PERSONA

--25.
SELECT NOMBRE, APELLIDO, SUM(EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM FECHA_NACIMIENTO)) 
FROM PERSONA
GROUP BY NOMBRE, APELLIDO
HAVING SUM(EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM FECHA_NACIMIENTO)) > 25
ORDER BY NOMBRE, APELLIDO

--26.
SELECT P.NOMBRE || ' ' || P.APELLIDO AS NOMBRECOMPLETO FROM PERSONA P, ALUMNO A, PROFESOR PR
WHERE A.DNI = P.DNI 
AND PR.DNI = P.DNI

--27.
SELECT SUM(A.CREDITOS) FROM ASIGNATURA A, TITULACION T
WHERE T.IDTITULACION = A.IDTITULACION 
AND UPPER(T.NOMBRE) = 'MATEMATICAS'

--28.
SELECT COUNT(A.IDASIGNATURA) FROM ASIGNATURA A, TITULACION T
WHERE T.IDTITULACION = A.IDTITULACION 
AND UPPER(T.NOMBRE) = 'MATEMATICAS'

--29.
SELECT P.NOMBRE, SUM(A.COSTEBASICO * A.CUATRIMESTRE) AS "TOTAL MATRICULA" FROM ALUMNO_ASIGNATURA AA, ASIGNATURA A, PERSONA P, ALUMNO AL
WHERE AA.IDASIGNATURA = A.IDASIGNATURA 
AND P.DNI = AL.DNI 
AND AL.IDALUMNO = AA.IDALUMNO
GROUP BY P.NOMBRE

--30.
SELECT A.NOMBRE, COUNT(AA.IDALUMNO) AS "ALUMNOS MATRICULAS" FROM ASIGNATURA A, ALUMNO AL, ALUMNO_ASIGNATURA AA
WHERE A.IDASIGNATURA = AA.IDASIGNATURA 
AND AL.IDALUMNO = AA.IDALUMNO
GROUP BY A.NOMBRE
