CREATE TABLE VEHICULOS
(
	Matricula VARCHAR2(7),
	Marca VARCHAR2(10) NOT NULL,
	Modelo VARCHAR2(10) NOT NULL,
	Fecha_Compra DATE,
	Precio_por_dia NUMBER(5, 2),
	CONSTRAINT PK_VEHICULOS PRIMARY KEY (Matricula)
);

CREATE TABLE CLIENTES
(
	DNI VARCHAR2(9),
	Nombre VARCHAR2(30) NOT NULL,
	Nacionalidad VARCHAR2(30),
	Fecha_Nacimiento DATE,
	Direccion VARCHAR2(50),
	CONSTRAINT PK_CLIENTE PRIMARY KEY (DNI),
	CONSTRAINT MAYOR CHECK(EXTRACT(YEAR FROM Fecha_Nacimiento) >= 2021)
);

CREATE TABLE ALQUILERES
(
	Matricula VARCHAR2(7) NOT NULL,
	DNI VARCHAR2(10) NOT NULL,
	FechaHora DATE,
	Num_dias NUMBER(2),
	Kilometros NUMBER(4),
	CONSTRAINT PK_ALQUILERES PRIMARY KEY (FechaHora),
	CONSTRAINT FK_VEHICULOS FOREIGN KEY (Matricula) REFERENCES VEHICULOS(Matricula),
	CONSTRAINT FK_CLIENTE FOREIGN KEY (DNI) REFERENCES CLIENTES(DNI)
);

ALTER TABLE CLIENTES ADD CONSTRAINT dni_correcto CHECK (regexp_like(DNI, '[0-9]{8}[-][A-Z]{1}'));
ALTER TABLE VEHICULOS ADD CONSTRAINT matricula_correcta CHECK (regexp_like(Matricula, '[0-9]{4}[A-Z]{3}'));
ALTER TABLE VEHICULOS ADD Kilometros NUMBER(6);
