--1.
SELECT nvl(idtitulacion,0), costebasico FROM ASIGNATURA
ORDER BY COSTEBASICO DESC, NOMBRE ASC

--2.
SELECT PE.NOMBRE, PE.APELLIDO FROM PERSONA PE, PROFESOR PR
WHERE PE.DNI=PR.DNI

--3. 
SELECT PE.NOMBRE, A.NOMBRE FROM ASIGNATURA A, PROFESOR PR,PERSONA PE
WHERE A.IDPROFESOR=PR.IDPROFESOR AND PR.DNI=PE.DNI AND UPPER(PE.CIUDAD) LIKE 'SEVILLA'

--4.
SELECT P.NOMBRE, P.APELLIDO FROM ALUMNO A, PERSONA P 
WHERE P.DNI=A.DNI

--5.
SELECT P.DNI, P.NOMBRE, P.APELLIDO FROM ALUMNO A, PERSONA P 
WHERE  P.DNI=A.DNI AND UPPER(P.CIUDAD) LIKE 'SEVILLA'

--6.
SELECT P.DNI, P.NOMBRE, P.APELLIDO FROM  ALUMNO AL, ASIGNATURA ASG, PERSONA P, ALUMNO_ASIGNATURA AA 
WHERE AA.IDASIGNATURA = ASG.IDASIGNATURA AND AA.IDALUMNO = AL.IDALUMNO AND AL.DNI=P.DNI AND UPPER(ASG.NOMBRE) LIKE 'SEGURIDAD VIAL'

--7.
SELECT T.IDTITULACION, AL.DNI FROM ALUMNO AL, ALUMNO_ASIGNATURA AA, ASIGNATURA ASG, TITULACION T 
WHERE AL.DNI LIKE '20202020A' AND AL.IDALUMNO = AA.IDALUMNO AND AA.IDASIGNATURA = ASG.IDASIGNATURA AND ASG.IDTITULACION = T.IDTITULACION AND AA.NUMEROMATRICULA > 0

--8.
SELECT ASG.NOMBRE FROM ASIGNATURA ASG, ALUMNO_ASIGNATURA AA, ALUMNO AL, PERSONA P 
WHERE UPPER(P.NOMBRE) LIKE 'ROSA' AND UPPER(P.APELLIDO) LIKE 'GARCIA' AND P.DNI=AL.DNI AND AA.IDALUMNO =AL.IDALUMNO AND AA.IDASIGNATURA = ASG.IDASIGNATURA 

--9.
SELECT AL.DNI FROM PROFESOR PR, PERSONA PE, ALUMNO AL, ALUMNO_ASIGNATURA AA, ASIGNATURA ASG
WHERE UPPER(PE.NOMBRE) LIKE 'JORGE' AND UPPER(PE.APELLIDO) LIKE 'SAENZ' AND PR.DNI=PE.DNI AND ASG.IDPROFESOR=PR.IDPROFESOR AND AA.IDASIGNATURA=ASG.IDASIGNATURA AND AL.IDALUMNO=AA.IDALUMNO

--10.
SELECT AL.DNI, PE2.NOMBRE, PE2.APELLIDO FROM PROFESOR PR, PERSONA PE, ALUMNO AL, ALUMNO_ASIGNATURA AA, ASIGNATURA ASG, PERSONA PE2
WHERE UPPER(PE.NOMBRE) LIKE 'JORGE' 
AND UPPER(PE.APELLIDO) LIKE 'SAENZ' 
AND PR.DNI=PE.DNI 
AND PE2.DNI = AL.DNI
AND ASG.IDPROFESOR=PR.IDPROFESOR 
AND AA.IDASIGNATURA=ASG.IDASIGNATURA 
AND AL.IDALUMNO=AA.IDALUMNO

--11. 
SELECT T.NOMBRE FROM TITULACION T, ASIGNATURA A 
WHERE T.IDTITULACION = A.IDTITULACION AND A.CREDITOS >= 4

--12.
SELECT A.NOMBRE , A.CREDITOS, T.NOMBRE FROM ASIGNATURA A, TITULACION T 
WHERE T.IDTITULACION = A.IDTITULACION AND A.CUATRIMESTRE = 1

--13.
SELECT ASG.NOMBRE, ASG.COSTEBASICO, PE.NOMBRE FROM  ASIGNATURA ASG, PERSONA PE, ALUMNO_ASIGNATURA AA, ALUMNO AL 
WHERE ASG.CREDITOS > 4.5 
AND ASG.IDASIGNATURA = AA.IDASIGNATURA 
AND AA.IDALUMNO = AL.IDALUMNO 
AND AL.DNI = PE.DNI 

--14.
SELECT PE.NOMBRE FROM PERSONA PE, PROFESOR PR, ASIGNATURA ASG
WHERE ASG.COSTEBASICO BETWEEN 25 AND 35 
AND ASG.IDPROFESOR = PR.IDPROFESOR 
AND PR.DNI = PE.DNI

--15.
SELECT PE.NOMBRE, AA.IDASIGNATURA FROM PERSONA PE, ALUMNO AL, ALUMNO_ASIGNATURA AA 
WHERE AA.IDALUMNO = AL.IDALUMNO 
AND AL.DNI = PE.DNI
AND (AA.IDASIGNATURA = '150212')  OR (AA.IDASIGNATURA = '130113' 
AND AA.IDALUMNO = AL.IDALUMNO AND AL.DNI = PE.DNI)

--16.
SELECT ASG.NOMBRE, T.NOMBRE FROM ASIGNATURA ASG, TITULACION T 
WHERE ASG.IDTITULACION = T.IDTITULACION 
AND ASG.CUATRIMESTRE = 2 
AND ASG.CREDITOS != 6

--17.
SELECT AL.DNI , ASG.NOMBRE, ASG.CREDITOS*10 AS NUMEROHORAS 
FROM ASIGNATURA ASG, ALUMNO_ASIGNATURA AA, ALUMNO AL 
WHERE ASG.IDASIGNATURA = AA.IDASIGNATURA 
AND AA.IDALUMNO = AL.IDALUMNO

--18.
SELECT PE.NOMBRE FROM PERSONA PE, ALUMNO AL, ALUMNO_ASIGNATURA AA 
WHERE PE.VARON = 0 
AND PE.DNI = AL.DNI 
AND AL.IDALUMNO = AA.IDALUMNO 
AND PE.CIUDAD LIKE 'Sevilla' 

--19.
SELECT ASG.NOMBRE FROM ASIGNATURA ASG, PROFESOR PR 
WHERE ASG.IDPROFESOR = PR.IDPROFESOR
AND ASG.CURSO = 1 
AND PR.IDPROFESOR = 'P101'

--20.
SELECT PE.NOMBRE FROM PERSONA PE, ALUMNO AL, ALUMNO_ASIGNATURA AA 
WHERE AA.IDALUMNO = AL.IDALUMNO 
AND AL.DNI = PE.DNI
AND AA.NUMEROMATRICULA >= 3 





