--Consultas multitabla interna
--1.
SELECT CLI.NOMBRE_CLIENTE, (E.NOMBRE || ' ' || E.APELLIDO1 || ' ' || E.APELLIDO2) AS NOMBREYAPELLIDO 
FROM CLIENTE CLI, EMPLEADO E
WHERE CLI.CODIGO_EMPLEADO_REP_VENTAS = E.CODIGO_EMPLEADO

--2.
SELECT DISTINCT CLI.NOMBRE_CLIENTE, CLI.NOMBRE_CONTACTO
FROM CLIENTE CLI, PAGO P, EMPLEADO E
WHERE CLI.CODIGO_CLIENTE = P.CODIGO_CLIENTE
AND CLI.CODIGO_EMPLEADO_REP_VENTAS = E.CODIGO_EMPLEADO

--3.
SELECT CLI.NOMBRE_CLIENTE, E.NOMBRE FROM CLIENTE CLI, EMPLEADO E, PAGO P
WHERE CLI.CODIGO_CLIENTE = P.CODIGO_CLIENTE(+)
AND CLI.CODIGO_EMPLEADO_REP_VENTAS = E.CODIGO_EMPLEADO
AND P.CODIGO_CLIENTE IS NULL

--4.
SELECT CLI.NOMBRE_CLIENTE, E.NOMBRE, O.CIUDAD FROM CLIENTE CLI, EMPLEADO E, OFICINA O
WHERE CLI.CODIGO_EMPLEADO_REP_VENTAS = E.CODIGO_EMPLEADO
AND E.CODIGO_OFICINA = O.CODIGO_OFICINA

--5.
SELECT DISTINCT CLI.NOMBRE_CLIENTE, E.NOMBRE, O.CIUDAD FROM CLIENTE CLI, EMPLEADO E, OFICINA O, PAGO P
WHERE CLI.CODIGO_EMPLEADO_REP_VENTAS = E.CODIGO_EMPLEADO
AND CLI.CODIGO_CLIENTE = P.CODIGO_CLIENTE(+)
AND E.CODIGO_OFICINA = O.CODIGO_OFICINA
AND P.CODIGO_CLIENTE IS NULL

--6.
SELECT DISTINCT O.LINEA_DIRECCION1 FROM CLIENTE CLI, EMPLEADO E, OFICINA O
WHERE CLI.CODIGO_EMPLEADO_REP_VENTAS = E.CODIGO_EMPLEADO
AND E.CODIGO_OFICINA = O.CODIGO_OFICINA
AND UPPER(CLI.CIUDAD) = 'FUENLABRADA'

--7.
SELECT DISTINCT CLI.NOMBRE_CLIENTE, E.NOMBRE, O.CIUDAD FROM CLIENTE CLI, EMPLEADO E, OFICINA O
WHERE CLI.CODIGO_EMPLEADO_REP_VENTAS = E.CODIGO_EMPLEADO
AND E.CODIGO_OFICINA = O.CODIGO_OFICINA

--8.
SELECT E.NOMBRE, J.NOMBRE FROM EMPLEADO E, EMPLEADO J
WHERE E.CODIGO_EMPLEADO = J.CODIGO_JEFE

--9.
SELECT DISTINCT CLI.NOMBRE_CLIENTE FROM CLIENTE CLI, PEDIDO P
WHERE CLI.CODIGO_CLIENTE = P.CODIGO_CLIENTE
AND P.FECHA_ESPERADA < P.FECHA_ENTREGA

--10.
SELECT DISTINCT GP.GAMA FROM GAMA_PRODUCTO GP, PRODUCTO P, DETALLE_PEDIDO DP, PEDIDO P, CLIENTE CLI
WHERE GP.GAMA = P.GAMA
AND DP.CODIGO_PRODUCTO = P.CODIGO_PRODUCTO
AND DP.CODIGO_PEDIDO = P.CODIGO_PEDIDO
AND CLI.CODIGO_CLIENTE = P.CODIGO_CLIENTE

--Consultas multitabla externa
--1.
SELECT CLI.* FROM CLIENTE CLI, PAGO P
WHERE CLI.CODIGO_CLIENTE = P.CODIGO_CLIENTE(+)
AND P.CODIGO_CLIENTE IS NULL

--2.
SELECT CLI.* FROM CLIENTE CLI, PEDIDO PE
WHERE CLI.CODIGO_CLIENTE = PE.CODIGO_CLIENTE(+)
AND PE.CODIGO_CLIENTE IS NULL

--3.
SELECT CLI.* FROM CLIENTE CLI, PEDIDO PE, PAGO P
WHERE CLI.CODIGO_CLIENTE = PE.CODIGO_CLIENTE(+)
AND CLI.CODIGO_CLIENTE = P.CODIGO_CLIENTE(+)
AND PE.CODIGO_CLIENTE IS NULL
AND P.CODIGO_CLIENTE IS NULL

--4.
SELECT E.* FROM EMPLEADO E, OFICINA O
WHERE O.CODIGO_OFICINA = E.CODIGO_OFICINA(+)
AND E.CODIGO_OFICINA IS NULL

--5.
SELECT E.* FROM EMPLEADO E, CLIENTE CLI
WHERE CLI.CODIGO_EMPLEADO_REP_VENTAS(+) = E.CODIGO_EMPLEADO
AND CLI.CODIGO_EMPLEADO_REP_VENTAS IS NULL

--6.
SELECT E.* FROM EMPLEADO E, OFICINA O, CLIENTE CLI
WHERE E.CODIGO_OFICINA(+) = O.CODIGO_OFICINA
AND CLI.CODIGO_EMPLEADO_REP_VENTAS(+) = E.CODIGO_EMPLEADO
AND E.CODIGO_OFICINA IS NULL
AND CLI.CODIGO_EMPLEADO_REP_VENTAS IS NULL

--7.
SELECT PR.* FROM PRODUCTO PR, DETALLE_PEDIDO DP
WHERE PR.CODIGO_PRODUCTO = DP.CODIGO_PRODUCTO(+)
AND DP.CODIGO_PRODUCTO IS NULL

--8.


--Subconsultas
--1. 
SELECT NOMBRE_CLIENTE FROM CLIENTE
WHERE LIMITE_CREDITO = (SELECT MAX(LIMITE_CREDITO) FROM CLIENTE)

--2.
SELECT NOMBRE, APELLIDO1, PUESTO FROM EMPLEADO
WHERE CODIGO_EMPLEADO IN 
(SELECT CODIGO_EMPLEADO_REP_VENTAS FROM CLIENTE WHERE CODIGO_EMPLEADO_REP_VENTAS IS NULL)

--3.
SELECT NOMBRE FROM PRODUCTO
WHERE PRECIO_VENTA = (SELECT MAX(PRECIO_VENTA) FROM PRODUCTO)

--4.
SELECT NOMBRE FROM PRODUCTO P, 
(SELECT CODIGO_PRODUCTO, MAX(SUMA) FROM (SELECT CODIGO_PRODUCTO, SUM(CANTIDAD) AS SUMA FROM DETALLE_PEDIDO)
GROUP BY CODIGO_PRODUCTO)  D
WHERE P.CODIGO_PRODUCTO = D.CODIGO_PRODUCTO

