--Apartado 1
INSERT INTO PERSONA
VALUES ('9460942F', 'Marian-Florian', 'Ristea', 'Sevilla', 'Francisco Noa Márquez', 13, '643637642', TO_DATE('30-10-2001', 'DD-MM-YYYY'), 1)    

INSERT INTO ALUMNO
VALUES ('A13245', '9460942F')

INSERT INTO ALUMNO_ASIGNATURA
VALUES ('A13245', '160002', 1)

--Apartado 2
INSERT INTO PERSONA
VALUES ('77222122K', 'Marta', 'López Martos', 'Sevilla', 'Calle Tarfia', 9, '615891432', TO_DATE('22-7-1981', 'DD-MM-YYYY'), 0)

INSERT INTO PROFESOR 
VALUES ('P100', '77222122K')

UPDATE ASIGNATURA
SET IDPROFESOR = 'P100'
WHERE IDASIGNATURA = '160002'

DELETE FROM PROFESOR
WHERE IDPROFESOR = 'P117'

DELETE FROM PERSONA
WHERE DNI = '25252525A'

--Apartado 3
SELECT IDALUMNO, IDASIGNATURA FROM ALUMNO_ASIGNATURA
WHERE NUMEROMATRICULA >= 3

CREATE TABLE ALUMNOS_MUYREPETIDORES
(
	IDASIGNATURA VARCHAR2(7),
	IDALUMNO VARCHAR2(11),
	NOMBRE VARCHAR2(30),
	APELLIDO VARCHAR2(30),
	TELEFONO VARCHAR2(9),
	CONSTRAINT PK_ALUMNOS_MUYREPETIDORES PRIMARY KEY (IDASIGNATURA)
);

INSERT INTO ALUMNOS_MUYREPETIDORES (IDASIGNATURA, IDALUMNO)
SELECT IDALUMNO, IDASIGNATURA FROM ALUMNO_ASIGNATURA
WHERE NUMEROMATRICULA >= 3

--Apartado 4
ALTER TABLE ALUMNOS_MUYREPETIDORES ADD OBSERVACIONES VARCHAR2(100);

UPDATE ALUMNOS_MUYREPETIDORES
SET OBSERVACIONES = 'Se encuentra en seguimiento'
WHERE IDALUMNO IN (SELECT IDALUMNO FROM PERSONA p, ALUMNO a 
WHERE CIUDAD LIKE 'Sevilla' AND p.DNI = a.DNI)
--No hay ningun alumno en muy repetidores que viva en Sevilla por lo tanto no hara ningun cambio

--Apartado 5
DELETE FROM ALUMNOS_MUYREPETIDORES
WHERE IDALUMNO IN (SELECT IDALUMNO FROM PERSONA p, ALUMNO a 
WHERE FECHA_NACIMIENTO LIKE '%11/1971%' AND p.DNI = a.DNI)
--No hay ninguna persona de 1971 por lo tanto no borrara a nadie

--6
CREATE TABLE RESUMEN_TITULACIONES
(
	NOMBRE_TITULACION VARCHAR2(6),
	IDTITULACION VARCHAR2(30),
	CONSTRAINT PK_RESUMEN_TITULACIONES PRIMARY KEY (IDTITULACION)
);

INSERT INTO RESUMEN_TITULACIONES
SELECT * FROM TITULACION

--Apartado 7
/*
 *7.1
 * No ya que si esta desactivado el autocommit hay que realizar manualmente
 * el guardado para poder ver los cambios.
 * 
 * 7.2
 * No a menós de que se hayan guardado los datos
 * 
 * 7.3
 * Si se podría volver con rollback
 */