--1.
SELECT NOMBRE, APELLIDOS, TELF 
FROM AFILIADOS
WHERE SEXO = 'H' 
AND NACIMIENTO < TO_DATE('1-1-1070', 'DD-MM-YYYY')

--2.
SELECT PESO, TALLA, PEZ
FROM CAPTURASSOLOS C
WHERE TALLA <= 45
UNION
SELECT PESO, TALLA, PEZ
FROM CAPTURASEVENTOS C2
WHERE TALLA <= 45
ORDER BY PEZ DESC, PESO DESC, TALLA DESC
--SI ESTA EN LAS 2 TABLAS SE USA EL INTERSECT

--3.
SELECT NOMBRE, APELLIDOS
FROM AFILIADOS A, PERMISOS P
WHERE A.FICHA = P.FICHA 
AND UPPER(P.LICENCIA) LIKE 'A%'
OR (A.TELF LIKE '9%' AND UPPER(A.DIRECCION) LIKE 'AVDA.')

--4.
SELECT LUGAR 
FROM LUGARES
WHERE UPPER(CAUCE) = 'RIO GENIL'
AND OBSERVACIONES IS NULL

--5.
SELECT DISTINCT A.NOMBRE, A.APELLIDOS, A2.FICHA
FROM AFILIADOS A, CAPTURASSOLOS C, AFILIADOS A2
WHERE A.FICHA = C.FICHA
AND C.AVAL1 = A2.FICHA

--6.
SELECT DISTINCT L.CAUCE, L.LUGAR
FROM LUGARES L, CAPTURASSOLOS C
WHERE L.LUGAR = C.LUGAR
AND UPPER(PEZ) = 'TENCA'

--7.
SELECT A.NOMBRE, A.APELLIDOS, P.POSICION, P.TROFEO
FROM AFILIADOS A, EVENTOS E, PARTICIPACIONES P
WHERE A.FICHA = P.FICHA
AND E.EVENTO = P.EVENTO
AND P.TROFEO IS NOT NULL
ORDER BY E.FECHA_EVENTO DESC

--8.
SELECT A.FICHA, A.NOMBRE, A.APELLIDOS, P.POSICION, P.TROFEO
FROM AFILIADOS A, EVENTOS E, PARTICIPACIONES P
WHERE A.FICHA = P.FICHA
AND E.EVENTO = P.EVENTO
AND UPPER(E.EVENTO) = 'SUPER BARBO'
ORDER BY P.POSICION 

--9.
SELECT DISTINCT A.NOMBRE, A.APELLIDOS, A2.FICHA
FROM AFILIADOS A, CAPTURASSOLOS C, AFILIADOS A2
WHERE A.FICHA = C.FICHA
AND C.AVAL2 = A2.FICHA

--10.
SELECT E.*
FROM AFILIADOS A, EVENTOS E, PARTICIPACIONES P
WHERE A.FICHA = P.FICHA
AND P.EVENTO = E.EVENTO
AND A.FICHA = 3796
AND EXTRACT(YEAR FROM E.FECHA_EVENTO) = '1995'
AND P.TROFEO IS NULL
ORDER BY E.FECHA_EVENTO DESC


