--1.
SELECT CODFAC, FECHA, NVL(DTO,0) FROM FACTURAS
WHERE IVA = 0

--2.
SELECT CODFAC FROM FACTURAS
WHERE IVA IS NULL

--3.
SELECT CODFAC, FECHA FROM FACTURAS
WHERE IVA = 0 OR IVA IS NULL

--4.
SELECT CODFAC, CODART FROM LINEAS_FAC
WHERE CANT < 5 AND DTO >= 25

--5.
SELECT DESCRIP FROM ARTICULOS
WHERE STOCK < STOCK_MIN

--6.
SELECT DISTINCT NVL(IVA,0) FROM FACTURAS

--7.
SELECT CODART, DESCRIP, NVL(STOCK_MIN,0) FROM ARTICULOS
WHERE STOCK IS NULL

--8.
SELECT DESCRIP FROM ARTICULOS
WHERE STOCK > POWER(STOCK_MIN, 3) AND PRECIO > 6

--9.
SELECT DISTINCT CODART FROM LINEAS_FAC
WHERE CODFAC BETWEEN 8 AND 10

--10.
SELECT NOMBRE, DIRECCION FROM CLIENTES

--11.
SELECT DISTINCT CODPUE FROM CLIENTES

--12.
SELECT DISTINCT CODPUE FROM CLIENTES
WHERE CODCLI < 25

--13.
SELECT NOMBRE FROM PROVINCIAS
WHERE UPPER(SUBSTR(NOMBRE, 2,1)) = 'O'

--14.
SELECT CODFAC, FECHA FROM FACTURAS
WHERE CODFAC BETWEEN 50 AND 100

--15.
SELECT NOMBRE, DIRECCION FROM CLIENTES
WHERE CODPOSTAL LIKE '12%'

--16.
SELECT FECHA FROM FACTURAS
WHERE CODCLI < 50

--17.
SELECT CODFAC, FECHA FROM FACTURAS
WHERE EXTRACT(MONTH FROM FECHA) = 6
AND EXTRACT(YEAR FROM FECHA) = 2004

--18.
SELECT CODFAC, FECHA FROM FACTURAS
WHERE EXTRACT(MONTH FROM FECHA) = 6
AND EXTRACT(YEAR FROM FECHA) = 2004
AND CODCLI BETWEEN 100 AND 250

--19.
SELECT CODFAC, FECHA FROM FACTURAS
WHERE CODCLI BETWEEN 90 AND 100
AND IVA = 0 OR IVA IS NULL

--20.
SELECT NOMBRE FROM PROVINCIAS
WHERE UPPER(SUBSTR(NOMBRE, LENGTH(NOMBRE), 1)) = 'S'

--21.
SELECT NOMBRE FROM CLIENTES
WHERE CODPOSTAL LIKE '02%' 
OR CODPOSTAL LIKE '11%' 
OR CODPOSTAL LIKE '21%'

--22.
SELECT * FROM ARTICULOS
WHERE STOCK > STOCK_MIN
AND (STOCK-STOCK_MIN) < 5

--23.
SELECT NOMBRE FROM PROVINCIAS
WHERE UPPER(NOMBRE) LIKE '%MA%'

--24.
SELECT CODART, DESCRIP, PRECIO, (PRECIO * 0.9) AS PRECIO_PROMOCION FROM ARTICULOS
WHERE PRECIO > 6000 AND (PRECIO * STOCK) > 60000



