--1.
SELECT DISTINCT C.NOMBRE, A.DESCRIP  
FROM CLIENTES C,ARTICULOS A,FACTURAS F, LINEAS_FAC L
WHERE C.CODCLI=F.CODCLI 
AND F.CODFAC=L.CODFAC 
AND L.CODART=A.CODART

--2.
SELECT DISTINCT PU.NOMBRE,PRO.NOMBRE 
FROM PUEBLOS PU ,PROVINCIAS PRO 
WHERE PRO.CODPRO=PU.CODPRO

--3.
SELECT DISTINCT C.NOMBRE,PU.NOMBRE,PRO.NOMBRE 
FROM CLIENTES C , PUEBLOS PU,PROVINCIAS PRO 
WHERE PRO.CODPRO=PU.CODPRO 
AND PU.CODPUE=C.CODPUE

--4.
SELECT DISTINCT PRO.NOMBRE 
FROM CLIENTES C , PUEBLOS PU,PROVINCIAS PRO
WHERE PRO.CODPRO=PU.CODPRO 
AND PU.CODPUE=C.CODPUE

--5.
SELECT DISTINCT A.DESCRIP
FROM ARTICULOS A ,LINEAS_FAC L  
WHERE A.CODART=L.CODART 
AND L.CANT>10

--6.
SELECT DISTINCT F.FECHA ,A.CODART,L.CANT 
FROM ARTICULOS A,LINEAS_FAC L,FACTURAS F 
WHERE A.CODART=L.CODART 
AND L.CODFAC=F.CODFAC
ORDER BY F.FECHA DESC,A.CODART,L.CANT ASC

--7.
SELECT F.CODFAC,F.FECHA FROM FACTURAS F , CLIENTES C
WHERE F.CODCLI=C.CODCLI
AND  CODPOSTAL LIKE('%7%')

--8.
FROM FACTURAS F ,CLIENTES C 
WHERE F.CODCLI=C.CODCLI

--9.
SELECT DISTINCT F.CODFAC,F.FECHA,F.IVA,F.DTO,C.NOMBRE
FROM FACTURAS F, CLIENTES C WHERE F.CODCLI=C.CODCLI 
AND  (IVA IS NULL OR IVA=0) OR DTO IS NULL

--10.
SELECT DISTINCT A.DESCRIP ,A.PRECIO,L.PRECIO,L.PRECIO
FROM ARTICULOS A,LINEAS_FAC L 
WHERE L.CODART=A.CODART
AND L.PRECIO<A.PRECIO

--11.
SELECT DISTINCT F.CODFAC,F.FECHA,F.IVA,F.DTO,A.DESCRIP,L.PRECIO,L.CANT,L.DTO
FROM FACTURAS F ,LINEAS_FAC L , ARTICULOS A 
WHERE F.CODFAC=L.CODFAC
AND L.CODART=A.CODART

--12.
SELECT F.CODFAC,F.FECHA,F.IVA,F.DTO,A.DESCRIP,L.PRECIO,L.CANT,L.DTO,C.NOMBRE
FROM FACTURAS F ,LINEAS_FAC L , ARTICULOS A ,CLIENTES C
WHERE C.CODCLI=F.CODCLI
AND F.CODFAC=L.CODFAC
AND L.CODART=A.CODART

--13.
SELECT C.NOMBRE 
FROM CLIENTES C,PUEBLOS PU,PROVINCIAS PRO 
WHERE C.CODPUE=PU.CODPUE
AND PU.CODPRO=PRO.CODPRO
AND UPPER(PRO.NOMBRE) LIKE ('%MA%')

--14.
SELECT F.CODCLI 
FROM FACTURAS F,LINEAS_FAC L,ARTICULOS A 
WHERE  F.CODFAC=L.CODFAC
AND L.CODART=A.CODART
AND L.CANT>0
AND A.STOCK<A.STOCK_MIN

--15.
SELECT DISTINCT A.DESCRIP
FROM ARTICULOS A,LINEAS_FAC L
WHERE A.CODART=L.CODART
AND L.CANT>1

--16.
SELECT DISTINCT A.DESCRIP, NVL(L.PRECIO, 0)- ((NVL(L.PRECIO,0) * NVL(L.DTO,0)) / 100)
FROM ARTICULOS A ,LINEAS_FAC L
WHERE L.CODART=A.CODART

--17.
SELECT DISTINCT A.DESCRIP
FROM ARTICULOS A,LINEAS_FAC L,FACTURAS F, CLIENTES C ,PUEBLOS PU,PROVINCIAS PRO 
WHERE A.CODART=L.CODART
AND L.CODFAC=F.CODFAC
AND F.CODCLI=C.CODCLI
AND C.CODPUE=PU.CODPUE
AND PU.CODPRO=PRO.CODPRO
AND UPPER(PRO.NOMBRE) LIKE('%A')

--18.
SELECT DISTINCT C.NOMBRE FROM CLIENTES C , FACTURAS F 
WHERE C.CODCLI=F.CODCLI 
AND  F.DTO>10

--19.
SELECT DISTINCT C.NOMBRE
FROM CLIENTES C,FACTURAS F,LINEAS_FAC L  
WHERE C.CODCLI=F.CODCLI 
AND F.CODFAC=L.CODFAC 
AND(F.DTO>10  OR L.DTO>10)
OR (F.DTO>10 AND L.DTO>10)

--20.
SELECT A.DESCRIP ,L.CANT,A.PRECIO FROM ARTICULOS A,LINEAS_FAC L,FACTURAS F,CLIENTES C
WHERE A.CODART=L.CODART
AND L.CODFAC = F.CODFAC
AND F.CODCLI = C.CODCLI
AND UPPER(C.NOMBRE) LIKE '%MARIA MERCEDES%'

