--1.
SELECT IDALUMNO FROM ALUMNO_ASIGNATURA
WHERE IDASIGNATURA NOT IN('150212', '130113')
							
--2.
SELECT NOMBRE FROM ASIGNATURA
WHERE CREDITOS > (SELECT CREDITOS
					FROM ASIGNATURA 
					WHERE UPPER(NOMBRE) = 'SEGURIDAD VIAL')
					
--3.
SELECT AA.IDALUMNO FROM ALUMNO_ASIGNATURA AA
WHERE AA.IDASIGNATURA LIKE '150212' 
AND AA.IDASIGNATURA IN (SELECT AA2.IDALUMNO FROM ALUMNO_ASIGNATURA AA2
						WHERE AA2.IDASIGNATURA LIKE '130113');
						
						
--4.
SELECT DISTINCT IDALUMNO FROM ALUMNO_ASIGNATURA
WHERE IDASIGNATURA IN (SELECT IDASIGNATURA 
						FROM ALUMNO_ASIGNATURA 
						WHERE IDASIGNATURA = '150212'
						OR IDASIGNATURA = '130113')
						
--5.
SELECT DISTINCT NOMBRE FROM ASIGNATURA
WHERE IDTITULACION = '130110' 
AND COSTEBASICO > (SELECT AVG(COSTEBASICO) FROM ASIGNATURA
					WHERE IDTITULACION = '130110')

--6.
SELECT IDALUMNO FROM ALUMNO_ASIGNATURA
WHERE IDASIGNATURA != '150212' AND IDASIGNATURA != '130113'

--7.
SELECT IDALUMNO FROM ALUMNO_ASIGNATURA
WHERE 

--8.
SELECT NOMBRE FROM ASIGNATURA
WHERE CREDITOS > (SELECT CREDITOS
					FROM ASIGNATURA 
					WHERE UPPER(NOMBRE) = 'SEGURIDAD VIAL')


